<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = $block->escapeHtml($block->getPageHeading());

if ($title): ?>
    <div id="title">
        <h1 class="<?= /* @escapeNotVerified */ $cssClass ?>">
            <?= /* @escapeNotVerified */ $title ?>
        </h1>
    </div>
<?php endif; ?>
